services:
  - type: web
    name: inventario-chiosburger-api
    runtime: node
    repo: https://github.com/Chios-Burger/inventario-chiosburger
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: chiosburguer.postgres.database.azure.com
      - key: DB_USER
        value: adminChios
      - key: DB_PASSWORD
        value: Burger2023
      - key: DB_NAME
        value: InventariosLocales
      - key: DB_PORT
        value: 5432
      - key: PORT
        generateValue: true
      - key: FRONTEND_URL
        value: https://inventario-chiosburger.netlify.app